package me.gserv.jython.enums;

public enum ForgeEventType {
    CONSTRUCTION, FINGERPRINT_VIOLATION,
    INITIALIZATION, INTER_MOD_COMMS,
    LOAD_COMPLETE, MISSING_MAPPING,
    MOD_DISABLED, MOD_ID_MAPPING,
    POST_INITIALIZATION, PRE_INITIALIZATION,
    SERVER_ABOUT_TO_START, SERVER_STARTED,
    SERVER_STARTING, SERVER_STOPPED,
    SERVER_STOPPING
}
